### PR TITLE
update the link to the license file

### PR DESCRIPTION
**Pull request by bollu**
quick update to the `README.md` to point to the right license file

### CODE REVIEW

**Comment by bollu** [comment]
@certik - could you merge this? I don't have the rights to

**Comment by sumith1896** [comment]
@bollu Sorry for asking in the wrong place. When do the Allowed failures in Travis expected to fail?

**Comment by bollu** [comment]
Since they're build on the nightlies, either the upstream packages themselves could be borked, or (AFAIK) a compiler bug / point version change could also theoretically cause the builds to fail.

**Comment by sumith1896** [comment]
Cool

**Pull request merged**
