### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by sumith1896**
We'll need to enable these for this repository too.

### CODE REVIEW

**Comment by bollu** [comment]
@isuruf - the build failing is bizarre

```
Unpacking GHC into /tmp/stack-setup4221/ ...
Running /bin/tar xf /home/travis/.stack/programs/x86_64-linux/ghc-7.8.4.tar.xz in directory /tmp/stack-setup4221/ exited with ExitFailure 2

xz: (stdin): Compressed data is corrupt
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
```

It looks like `stack` (the build tool) got a corrupted version of the `GHC` compiler. Could you rerun the CI to check?

**Comment by certik** [comment]
Sure, I restarted the two failed tests.

**Comment by bollu** [comment]
@certik - cool, build passes :)

**Comment by sumith1896** [comment]
I cannot merge this PR.
Could you also activate codeclimate for this repo while merging this.
/cc @certik @isuruf

**Comment by certik** [comment]
@Sumith1896 I fixed the teams, you should be able to merge it now.

**Comment by sumith1896** [comment]
Thanks @certik 
Activated codeclimate https://codeclimate.com/github/symengine/symengine.hs
Merging...

**Pull request merged**
